version: '2.4'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run dev
    ports:
      - '3030:3030/tcp'
      - '9229:9229/tcp'
    volumes:
      - .:/opt:delegated
    environment:
      - MONGO_URI
      - PORT=3030